/**
 * app.js — loads the content files, boots the graph, and owns everything
 * outside the canvas: the modal, the hash router, search, the text view,
 * and the accessible link list.
 *
 * Content contract: content/nodes.json lists paths under content/nodes/. The
 * folder a file sits in is its parent circle (see fromPath), a folder's own
 * text lives in that folder's index.md, and the filename is the node's id and
 * URL. nodes.json is generated by tools/build-node-list.py via a GitHub Action.
 */
(function () {
  "use strict";

  var CONTENT_DIR = "content/nodes/";
  var ROOT_ID = "home"; // content/nodes/index.md — the centre circle
  var MANIFEST = "content/nodes.json";

  // Friendly color names → the --c-* tokens in css/style.css.
  var COLORS = {
    blue: "#3867d6",
    purple: "#7655c5",
    green: "#27866e",
    orange: "#bd7623",
    pink: "#c65370",
    teal: "#258789",
    slate: "#657184",
  };

  var el = {};
  var graph = null;
  var nodes = [];          // ordered, tree-ish
  var byId = Object.create(null);
  var warnings = [];
  var currentOpen = null;
  var lastFocused = null;
  var textViewLastFocused = null;
  var searchActiveIndex = -1;

  /* ---------------- boot ---------------- */

  document.addEventListener("DOMContentLoaded", function () {
    el.canvas = document.getElementById("canvas");
    el.backdrop = document.getElementById("backdrop");
    el.modal = document.getElementById("modal");
    el.modalBody = document.getElementById("modal-body");
    el.closeBtn = document.getElementById("modal-close");
    el.searchWrap = document.querySelector(".search-wrap");
    el.searchToggle = document.getElementById("search-toggle");
    el.search = document.getElementById("search");
    el.results = document.getElementById("search-results");
    el.srNav = document.getElementById("sr-nav");
    el.warnings = document.getElementById("warnings");
    el.textView = document.getElementById("text-view");
    el.textBody = document.getElementById("text-view-body");
    el.hint = document.getElementById("hint");
    el.loading = document.getElementById("loading");

    wireChrome();

    loadContent()
      .then(function (list) {
        nodes = list;
        list.forEach(function (n) {
          byId[n.id] = n;
        });

        if (!nodes.length) {
          fail(
            "No nodes loaded. Check that content/nodes.json lists at least one file, and that you are viewing this through a web server (see HOW-TO-ADD-A-NODE.md)."
          );
          return;
        }

        graph = window.Graph.create({
          canvas: el.canvas,
          nodes: nodes,
          onSelect: handleNodeClick,
          onHover: function () {},
        });
        graph.init(nodes);
        el.canvas.setAttribute("data-ready", "true");

        buildSrNav();
        buildTextView();
        showWarnings();
        if (el.loading) el.loading.remove();

        window.addEventListener("resize", debounce(function () {
          graph.resize();
        }, 120));

        window.addEventListener("popstate", syncFromHash);
        window.addEventListener("hashchange", syncFromHash);
        syncFromHash();
      })
      .catch(function (err) {
        fail(
          "Could not load the site content. If you opened this file directly from your " +
            "computer, that's the cause — run `python3 -m http.server 8000` in the portfolio " +
            "folder and open http://localhost:8000 instead. (" + err.message + ")"
        );
      });
  });

  function fail(message) {
    if (el.loading) el.loading.remove();
    warnings.push(message);
    showWarnings();
  }

  /* ---------------- content loading ---------------- */

  function loadContent() {
    return fetchText(MANIFEST).then(function (raw) {
      var files = parseManifest(raw);
      return Promise.all(
        files.map(function (file) {
          var name = file.replace(/^\/+/, "");
          if (!/\.md$/i.test(name)) name += ".md";
          return fetchText(CONTENT_DIR + name)
            .then(function (text) {
              return { file: name, text: text };
            })
            .catch(function () {
              warnings.push(
                'Could not find "' + name + '". It is listed in content/nodes.json but the ' +
                  "file is missing from content/nodes/ — check the spelling."
              );
              return null;
            });
        })
      ).then(assemble);
    });
  }

  function parseManifest(raw) {
    // Allow // comments so the file can be annotated.
    var cleaned = raw
      .split("\n")
      .filter(function (line) {
        return line.trim().indexOf("//") !== 0;
      })
      .join("\n");

    var data;
    try {
      data = JSON.parse(cleaned);
    } catch (e) {
      throw new Error(
        "content/nodes.json is not valid JSON (" + e.message + "). A missing or extra comma is the usual cause."
      );
    }

    var list = Array.isArray(data) ? data : data.nodes;
    if (!Array.isArray(list)) {
      throw new Error('content/nodes.json must contain a "nodes" list of filenames.');
    }
    return list.filter(function (x) {
      return typeof x === "string" && x.trim();
    });
  }

  /**
   * The folder a file sits in IS its parent — there is no `parent:` setting.
   *
   *   index.md                        → the centre circle
   *   work/index.md                   → "work", hanging off the centre
   *   work/segmentation.md            → "segmentation", hanging off "work"
   *   skills/programming/python.md    → "python", hanging off "programming"
   *
   * The id is the filename (or the folder name, for an index.md), which is
   * also the URL — so filenames must be unique across the whole tree.
   */
  function fromPath(relPath) {
    var parts = relPath.replace(/\.md$/i, "").split("/").filter(Boolean);

    // Dropping "index" leaves the folder name in its place, so both kinds of
    // file are handled by the same two lines below.
    if (parts[parts.length - 1] === "index") parts.pop();
    if (!parts.length) return { id: ROOT_ID, parent: null }; // content/nodes/index.md

    var folders = parts.slice(0, -1);
    return {
      id: parts[parts.length - 1],
      parent: folders.length ? folders[folders.length - 1] : ROOT_ID,
    };
  }

  function assemble(loaded) {
    var out = [];
    var seen = Object.create(null);

    loaded.forEach(function (entry) {
      if (!entry) return;
      var placed = fromPath(entry.file);
      var id = placed.id;
      var parsed = window.Markdown.parse(entry.text);
      var meta = parsed.meta;

      if (meta.parent) {
        warnings.push(
          '"' + entry.file + '" has a `parent:` line, which is no longer used — the folder a ' +
            "file sits in is its parent now. Move the file instead, and delete that line."
        );
      }

      if (seen[id]) {
        warnings.push(
          'Two files are both called "' + id + '.md" (in different folders). Filenames are ' +
            "web addresses, so they have to be unique across every folder — rename one. " +
            "The second one was skipped."
        );
        return;
      }
      seen[id] = true;

      if (meta.draft === "true") return;

      var node = {
        id: id,
        title: meta.title || id,
        parent: placed.parent,
        order: meta.order !== undefined ? parseFloat(meta.order) : 10000,
        color: resolveColor(meta.color),
        tag: meta.tag || "",
        metric: meta.metric || "",
        metricLabel: meta["metric-label"] || "",
        size: meta.size || "",
        angle: meta.angle !== undefined ? parseFloat(meta.angle) : undefined,
        body: parsed.body,
        hasBody: parsed.body.length > 0,
      };
      out.push(node);
    });

    // Validate parents once every node is known.
    var ids = Object.create(null);
    out.forEach(function (n) {
      ids[n.id] = true;
    });
    var roots = [];
    out.forEach(function (n) {
      if (!n.parent) {
        roots.push(n);
      } else if (!ids[n.parent]) {
        warnings.push(
          '"' + n.id + '.md" sits in a folder called "' + n.parent + '", but that folder has ' +
            'no index.md, so there is no circle for it to hang off. Add "' + n.parent +
            '/index.md". For now it has been attached to the centre.'
        );
        n.parent = roots.length ? roots[0].id : null;
      }
    });

    if (roots.length === 0 && out.length) {
      warnings.push(
        'No centre circle found — content/nodes/index.md is missing. Using "' + out[0].id + '" as the centre.'
      );
      out[0].parent = null;
    } else if (roots.length > 1) {
      warnings.push(
        "More than one centre circle (" +
          roots.map(function (r) { return r.id; }).join(", ") +
          '). "' + roots[0].id + '" is the centre; the rest were attached to it.'
      );
      roots.slice(1).forEach(function (r) {
        r.parent = roots[0].id;
      });
    }

    // `order:` from the settings block decides where a circle sits among its
    // siblings. Sorting the whole list by it works because the graph only ever
    // compares nodes that share a parent, and Array.sort is stable.
    out = out
      .map(function (n, i) { return { n: n, i: i }; })
      .sort(function (a, b) { return a.n.order - b.n.order || a.i - b.i; })
      .map(function (x) { return x.n; });

    // A node with no `color:` takes its parent's, so a branch is one hue.
    var children = Object.create(null);
    out.forEach(function (n) {
      if (!n.parent) return;
      (children[n.parent] = children[n.parent] || []).push(n);
    });
    (function inherit(node) {
      if (!node.color) node.color = "#1d1d1f";
      (children[node.id] || []).forEach(function (kid) {
        if (!kid.color) kid.color = node.color;
        inherit(kid);
      });
    })(roots[0] || out[0]);

    return out;
  }

  function resolveColor(value) {
    if (!value) return null;
    var key = value.trim().toLowerCase();
    if (COLORS[key]) return COLORS[key];
    if (/^#[0-9a-f]{3,6}$/i.test(key)) return key;
    warnings.push(
      'Unknown color "' + value + '". Use one of: ' + Object.keys(COLORS).join(", ") + "."
    );
    return null;
  }

  function fetchText(url) {
    return fetch(url, { cache: "no-cache" }).then(function (res) {
      if (!res.ok) throw new Error(url + " → HTTP " + res.status);
      return res.text();
    });
  }

  /* ---------------- routing ---------------- */

  function hashId() {
    var m = location.hash.match(/^#\/(.+)$/);
    return m ? decodeURIComponent(m[1]) : null;
  }

  function syncFromHash() {
    var id = hashId();
    if (id === currentOpen) return;
    if (id && byId[id] && byId[id].hasBody) {
      openNode(id);
    } else {
      closeModal(false);
      if (id && byId[id]) graph.flyTo(id);
    }
  }

  function navigate(id) {
    var target = id ? "#/" + encodeURIComponent(id) : location.pathname + location.search;
    if (location.hash === (id ? "#/" + encodeURIComponent(id) : "")) return;
    history.pushState(null, "", target);
    syncFromHash();
  }

  function handleNodeClick(node) {
    if (node.hasBody) {
      navigate(node.id);
    } else {
      graph.select(node.id);
      graph.flyTo(node.id);
    }
  }

  /* ---------------- modal ---------------- */

  function openNode(id) {
    var node = byId[id];
    if (!node) return;
    currentOpen = id;
    graph.select(id);

    // Start moving the node toward the middle, but do not make the dialog wait
    // for the full camera animation before it becomes available.
    graph.flyTo(id, function () {
      renderModal(node);
    });
    // A short handoff preserves the visual connection to the selected node
    // while keeping the interface responsive. renderModal is idempotent.
    setTimeout(function () {
      renderModal(node);
    }, 160);
  }

  function renderModal(node) {
    if (currentOpen !== node.id) return;
    if (el.backdrop.getAttribute("data-open") === "true" && el.modal.dataset.node === node.id) {
      return;
    }

    lastFocused = document.activeElement;
    el.modal.dataset.node = node.id;
    el.modal.style.setProperty("--accent", node.color || "#1d1d1f");

    var html = "";
    if (node.tag) html += '<p class="modal-tag">' + escapeHtml(node.tag) + "</p>";
    html += '<h1 class="modal-title" id="modal-title">' + escapeHtml(node.title) + "</h1>";
    if (node.metric) {
      html +=
        '<div class="modal-metric"><span class="modal-metric-value">' +
        escapeHtml(node.metric) + "</span>" +
        (node.metricLabel
          ? '<span class="modal-metric-label">' + escapeHtml(node.metricLabel) + "</span>"
          : "") +
        "</div>";
    }
    html += '<div class="prose">' + window.Markdown.render(node.body) + "</div>";

    var related = nodes.filter(function (n) {
      return n.parent === node.id && n.hasBody;
    });
    if (related.length) {
      html +=
        '<nav class="modal-related"><h2>Inside this branch</h2><ul>' +
        related
          .map(function (r) {
            return '<li><a href="#/' + encodeURIComponent(r.id) + '">' + escapeHtml(r.title) + "</a></li>";
          })
          .join("") +
        "</ul></nav>";
    }

    el.modalBody.innerHTML = html;
    el.modalBody.scrollTop = 0;
    el.backdrop.setAttribute("data-open", "true");
    el.backdrop.removeAttribute("hidden");
    document.body.classList.add("modal-open");
    el.closeBtn.focus();
  }

  function closeModal(updateHash) {
    if (el.backdrop.getAttribute("data-open") !== "true" && currentOpen === null) return;
    currentOpen = null;
    el.backdrop.setAttribute("data-open", "false");
    el.backdrop.setAttribute("hidden", "");
    el.modal.dataset.node = "";
    document.body.classList.remove("modal-open");
    if (graph) graph.select(null);
    if (updateHash !== false) navigate(null);
    if (lastFocused && document.contains(lastFocused)) {
      lastFocused.focus();
      lastFocused = null;
    }
  }

  /* ---------------- chrome: controls, search, text view ---------------- */

  function wireChrome() {
    el.closeBtn.addEventListener("click", function () {
      closeModal();
    });

    el.backdrop.addEventListener("mousedown", function (e) {
      if (e.target === el.backdrop) closeModal();
    });

    document.addEventListener("keydown", function (e) {
      if (e.key === "Escape") {
        if (el.textView.getAttribute("data-open") === "true") {
          toggleTextView(false);
        } else if (currentOpen) {
          closeModal();
        } else if (el.searchWrap.getAttribute("data-expanded") === "true") {
          setSearchOpen(false, true);
        }
        return;
      }
      // "/" jumps to search, the way most map/search UIs behave.
      if (
        e.key === "/" &&
        document.activeElement !== el.search &&
        !currentOpen &&
        el.textView.getAttribute("data-open") !== "true"
      ) {
        e.preventDefault();
        setSearchOpen(true);
      }
      if (e.key === "Tab" && currentOpen) {
        trapFocus(e, el.modal);
      } else if (e.key === "Tab" && el.textView.getAttribute("data-open") === "true") {
        trapFocus(e, el.textView);
      }
    });

    document.getElementById("zoom-in").addEventListener("click", function () {
      graph && graph.zoomBy(1.3);
    });
    document.getElementById("zoom-out").addEventListener("click", function () {
      graph && graph.zoomBy(1 / 1.3);
    });
    document.getElementById("zoom-reset").addEventListener("click", function () {
      if (!graph) return;
      graph.select(null);
      graph.reset();
    });

    document.getElementById("text-toggle").addEventListener("click", function () {
      toggleTextView(el.textView.getAttribute("data-open") !== "true");
    });
    document.getElementById("text-view-close").addEventListener("click", function () {
      toggleTextView(false);
    });

    el.searchToggle.addEventListener("click", function () {
      var isOpen = el.searchWrap.getAttribute("data-expanded") === "true";
      setSearchOpen(!isOpen, isOpen);
    });
    el.search.addEventListener("focus", function () {
      if (el.searchWrap.getAttribute("data-expanded") !== "true") setSearchOpen(true);
    });
    el.search.addEventListener("input", function () {
      searchActiveIndex = -1;
      renderResults(searchNodes(el.search.value), el.search.value);
    });
    el.search.addEventListener("keydown", function (e) {
      var buttons = el.results.querySelectorAll("button");
      if ((e.key === "ArrowDown" || e.key === "ArrowUp") && buttons.length) {
        e.preventDefault();
        var direction = e.key === "ArrowDown" ? 1 : -1;
        var next = searchActiveIndex + direction;
        if (next < 0) next = buttons.length - 1;
        if (next >= buttons.length) next = 0;
        setActiveResult(next);
        return;
      }
      if (e.key === "Enter") {
        var chosen = buttons[searchActiveIndex] || buttons[0];
        if (chosen) {
          e.preventDefault();
          chosen.click();
        }
      }
    });
    document.addEventListener("click", function (e) {
      if (!el.searchWrap.contains(e.target)) setSearchOpen(false, false);
    });

    // Dismiss the "drag to explore" hint the first time the user does anything.
    ["pointerdown", "wheel", "keydown"].forEach(function (evt) {
      window.addEventListener(evt, function once() {
        if (el.hint) el.hint.setAttribute("data-hidden", "true");
        window.removeEventListener(evt, once);
      });
    });
  }

  function setSearchOpen(open, returnFocus) {
    var isOpen = el.searchWrap.getAttribute("data-expanded") === "true";
    if (open === isOpen) {
      if (open && document.activeElement !== el.search) el.search.focus();
      return;
    }

    el.searchWrap.setAttribute("data-expanded", open ? "true" : "false");
    el.searchToggle.setAttribute("aria-expanded", open ? "true" : "false");
    document.body.classList.toggle("search-open", open);

    if (open) {
      el.search.removeAttribute("tabindex");
      window.requestAnimationFrame(function () {
        el.search.focus();
      });
      return;
    }

    el.search.value = "";
    renderResults([], "");
    el.search.setAttribute("tabindex", "-1");
    el.search.blur();
    if (returnFocus) el.searchToggle.focus();
  }

  function trapFocus(e, container) {
    var focusables = container.querySelectorAll(
      'a[href], button:not([disabled]), input, [tabindex]:not([tabindex="-1"])'
    );
    if (!focusables.length) return;
    var first = focusables[0];
    var last = focusables[focusables.length - 1];
    if (e.shiftKey && document.activeElement === first) {
      e.preventDefault();
      last.focus();
    } else if (!e.shiftKey && document.activeElement === last) {
      e.preventDefault();
      first.focus();
    }
  }

  function searchNodes(query) {
    var q = query.trim().toLowerCase();
    if (!q) return [];
    return nodes
      .filter(function (n) {
        return (
          n.title.toLowerCase().indexOf(q) !== -1 ||
          String(n.tag || "").toLowerCase().indexOf(q) !== -1
        );
      })
      .slice(0, 8);
  }

  function renderResults(list, query) {
    var q = String(query || "").trim();
    searchActiveIndex = -1;
    el.search.removeAttribute("aria-activedescendant");

    if (!list.length && !q) {
      el.results.innerHTML = "";
      el.results.setAttribute("hidden", "");
      el.search.setAttribute("aria-expanded", "false");
      return;
    }

    if (!list.length) {
      el.results.innerHTML = '<li class="search-empty">No nodes match “' + escapeHtml(q) + '”.</li>';
      el.results.removeAttribute("hidden");
      el.search.setAttribute("aria-expanded", "true");
      return;
    }

    el.results.innerHTML = list
      .map(function (n, index) {
        return (
          '<li role="presentation"><button id="search-option-' + index + '" role="option" ' +
          'aria-selected="false" type="button" data-id="' + escapeHtml(n.id) + '">' +
          '<span class="dot" style="background:' + (n.color || "#1d1d1f") + '"></span>' +
          highlightMatch(n.title, q) +
          (n.hasBody ? "" : '<span class="result-note">label</span>') +
          "</button></li>"
        );
      })
      .join("");
    el.results.removeAttribute("hidden");
    el.search.setAttribute("aria-expanded", "true");
    Array.prototype.forEach.call(el.results.querySelectorAll("button"), function (btn) {
      btn.addEventListener("click", function () {
        var node = byId[btn.dataset.id];
        setSearchOpen(false, false);
        if (node.hasBody) navigate(node.id);
        else {
          graph.select(node.id);
          graph.flyTo(node.id);
        }
      });
    });
  }

  function setActiveResult(index) {
    var buttons = el.results.querySelectorAll("button");
    if (!buttons.length) return;
    searchActiveIndex = index;
    Array.prototype.forEach.call(buttons, function (button, i) {
      var active = i === index;
      button.setAttribute("data-active", active ? "true" : "false");
      button.setAttribute("aria-selected", active ? "true" : "false");
      if (active) button.scrollIntoView({ block: "nearest" });
    });
    el.search.setAttribute("aria-activedescendant", buttons[index].id);
  }

  function highlightMatch(text, query) {
    var value = String(text);
    var q = String(query || "").trim().toLowerCase();
    var index = value.toLowerCase().indexOf(q);
    if (!q || index === -1) return escapeHtml(value);
    return (
      escapeHtml(value.slice(0, index)) +
      "<mark>" + escapeHtml(value.slice(index, index + q.length)) + "</mark>" +
      escapeHtml(value.slice(index + q.length))
    );
  }

  function buildSrNav() {
    el.srNav.innerHTML =
      "<h2>All sections</h2><ul>" +
      nodes
        .filter(function (n) {
          return n.hasBody;
        })
        .map(function (n) {
          return '<li><a href="#/' + encodeURIComponent(n.id) + '">' + escapeHtml(n.title) + "</a></li>";
        })
        .join("") +
      "</ul>";
  }

  function buildTextView() {
    var order = [];
    var root = nodes.filter(function (n) {
      return !n.parent;
    })[0];
    (function walk(node) {
      if (!node) return;
      order.push(node);
      nodes
        .filter(function (n) {
          return n.parent === node.id;
        })
        .forEach(walk);
    })(root);

    el.textBody.innerHTML = order
      .filter(function (n) {
        return n.hasBody;
      })
      .map(function (n) {
        return (
          '<section class="text-section" id="text-' + escapeHtml(n.id) + '">' +
          (n.tag ? '<p class="modal-tag">' + escapeHtml(n.tag) + "</p>" : "") +
          "<h2>" + escapeHtml(n.title) + "</h2>" +
          (n.metric
            ? '<p class="text-metric"><strong>' + escapeHtml(n.metric) + "</strong> " +
              escapeHtml(n.metricLabel) + "</p>"
            : "") +
          '<div class="prose">' + window.Markdown.render(n.body) + "</div>" +
          "</section>"
        );
      })
      .join("");
  }

  function toggleTextView(open) {
    el.textView.setAttribute("data-open", open ? "true" : "false");
    document.getElementById("text-toggle").setAttribute("aria-expanded", open ? "true" : "false");
    if (open) {
      textViewLastFocused = document.activeElement;
      el.textView.removeAttribute("hidden");
      document.body.classList.add("modal-open");
      el.textView.scrollTop = 0;
      document.getElementById("text-view-close").focus();
    } else {
      el.textView.setAttribute("hidden", "");
      if (!currentOpen) document.body.classList.remove("modal-open");
      if (textViewLastFocused && document.contains(textViewLastFocused)) {
        textViewLastFocused.focus();
        textViewLastFocused = null;
      }
    }
  }

  function showWarnings() {
    if (!warnings.length) {
      el.warnings.setAttribute("hidden", "");
      return;
    }
    el.warnings.innerHTML =
      '<button type="button" class="warn-close" aria-label="Dismiss">×</button>' +
      "<strong>Content problem" + (warnings.length > 1 ? "s" : "") + "</strong><ul>" +
      warnings
        .map(function (w) {
          return "<li>" + escapeHtml(w) + "</li>";
        })
        .join("") +
      "</ul>";
    el.warnings.removeAttribute("hidden");
    el.warnings.querySelector(".warn-close").addEventListener("click", function () {
      el.warnings.setAttribute("hidden", "");
    });
    if (window.console) console.warn("[portfolio] content warnings:", warnings);
  }

  /* ---------------- utils ---------------- */

  function escapeHtml(s) {
    return String(s)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }

  function debounce(fn, ms) {
    var t;
    return function () {
      clearTimeout(t);
      t = setTimeout(fn, ms);
    };
  }
})();
