/**
 * detail.js — renders a full case-study page (projects/<id>/index.html).
 *
 * The shell is generated by tools/build-node-list.py and already contains a
 * static, crawlable version of the study. This script replaces that body with
 * the live render of content/details/<id>.md, which adds charts and keeps the
 * numbers in step with content/semantic.json.
 */
(function () {
  "use strict";

  var id = document.body.getAttribute("data-detail");
  var body = document.getElementById("detail-body");
  if (!id || !body) return;

  function fetchText(url) {
    return fetch(url, { cache: "no-cache" }).then(function (res) {
      if (!res.ok) throw new Error(url + " → HTTP " + res.status);
      return res.text();
    });
  }

  fetchText("/content/semantic.json")
    .then(function (raw) {
      window.Markdown.setMetrics((JSON.parse(raw) || {}).metrics || {});
    })
    .catch(function () {})
    .then(function () {
      return fetchText("/content/details/" + encodeURIComponent(id) + ".md");
    })
    .then(function (raw) {
      var parsed = window.Markdown.parse(raw);
      body.innerHTML = window.Markdown.render(parsed.body);
      body.setAttribute("data-rendered", "true");
      if (window.goatcounter && typeof window.goatcounter.count === "function") {
        window.goatcounter.count({ path: "detail/" + id, title: "detail: " + id, event: true });
      }
    })
    .catch(function () {
      // The static version stays in place; nothing to do.
    });
})();
