#!/usr/bin/env python3
"""
Regenerates content/nodes.json by walking content/nodes/.

The website can't discover files on its own — GitHub Pages serves files but
can't list a folder — so it needs this list handed to it. A GitHub Action runs
this on every push, so you normally never think about it.

To run it yourself:  python3 tools/build-node-list.py

Rules:
  - a folder is a circle; its own text lives in that folder's index.md
  - content/nodes/index.md is the centre circle
  - files and folders starting with _ are ignored (e.g. _TEMPLATE.md)
  - `order:` in a file's settings block decides where it sits among its
    siblings; anything without one goes last, alphabetically
"""

import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
NODES = ROOT / "content" / "nodes"
MANIFEST = ROOT / "content" / "nodes.json"
DEFAULT_ORDER = 10_000


def read_order(path):
    """Pull `order:` out of the settings block at the top of a node file."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return DEFAULT_ORDER
    m = re.match(r"^---\n(.*?)\n---", text, re.S)
    if not m:
        return DEFAULT_ORDER
    m2 = re.search(r"^order:\s*(-?\d+)\s*$", m.group(1), re.M)
    return int(m2.group(1)) if m2 else DEFAULT_ORDER


def hidden(name):
    return name.startswith("_") or name.startswith(".")


def walk(directory):
    """Depth-first: a circle, then its children in `order:` sequence."""
    out = []

    index = directory / "index.md"
    if index.exists():
        out.append(index)

    entries = []
    for child in directory.iterdir():
        if hidden(child.name):
            continue
        if child.is_dir():
            entries.append((read_order(child / "index.md"), child.name, child))
        elif child.suffix == ".md" and child.name != "index.md":
            entries.append((read_order(child), child.name, child))

    for _, _, child in sorted(entries, key=lambda e: (e[0], e[1])):
        if child.is_dir():
            out.extend(walk(child))
        else:
            out.append(child)

    return out


def main():
    if not NODES.is_dir():
        sys.exit("No content/nodes/ folder found at %s" % NODES)

    files = walk(NODES)
    paths = [f.relative_to(NODES).as_posix() for f in files]

    if not paths:
        sys.exit("Found no node files — refusing to write an empty list.")
    if "index.md" not in paths:
        sys.exit("content/nodes/index.md is missing — that file is the centre circle.")

    payload = (
        "{\n"
        '  "//": "AUTO-GENERATED by tools/build-node-list.py — do not edit by hand. '
        'Add a .md file under content/nodes/ and this list updates itself on push.",\n'
        '\n  "nodes": [\n'
        + ",\n".join('    "%s"' % p for p in paths)
        + "\n  ]\n}\n"
    )

    previous = MANIFEST.read_text(encoding="utf-8") if MANIFEST.exists() else ""
    if previous == payload:
        print("nodes.json already up to date (%d nodes)" % len(paths))
        return

    MANIFEST.write_text(payload, encoding="utf-8")
    print("nodes.json updated — %d nodes" % len(paths))


if __name__ == "__main__":
    main()
